# Programme Calcul de la matrice #

In [143]:
function calcul(v,w,C::Matrix{Int8})
    I=fill((0,0),size(C))
    L=fill([0,0,0,0],size(C))
    for i in 2:(size(C,2))
        for j in 1:(size(C,1))
            if (j>w[i-1])
                C[j,i] = max(C[j-w[i-1],i-1]+v[i-1],C[j,i-1])
                if(C[j-w[i-1],i-1]+v[i-1]>C[j,i-1])
                     I[j,i] = (j-w[i-1],i-1) 
                     L[j,i][i-1] = 1
                     L[j,i] = L[j,i-1] + L[j,i]
                else
                    I[j,i] = (j,i-1)  
                end
            else
                C[j,i] = C[j,i-1]
                I[j,i] = (j,i-1)
            end
        end
    end
    return C,I,L
end

calcul (generic function with 3 methods)

**Calcul de la matrice**

In [141]:
n = 4
Q = 10
C = zeros(Int8, Q+1,n+1);
vi = [42,40,12,25]
wi = [7,4,3,5]

4-element Vector{Int64}:
 7
 4
 3
 5

In [144]:
C,I,J = calcul(vi,wi,C)
C

11×5 Matrix{Int8}:
 0   0   0   0   0
 0   0   0   0   0
 0   0   0   0   0
 0   0   0  12  12
 0   0  40  40  40
 0   0  40  40  40
 0   0  40  40  40
 0  42  42  52  52
 0  42  42  52  52
 0  42  42  52  65
 0  42  42  54  65

In [145]:
I

11×5 Matrix{Tuple{Int64, Int64}}:
 (0, 0)  (1, 1)  (1, 2)   (1, 3)  (1, 4)
 (0, 0)  (2, 1)  (2, 2)   (2, 3)  (2, 4)
 (0, 0)  (3, 1)  (3, 2)   (3, 3)  (3, 4)
 (0, 0)  (4, 1)  (4, 2)   (1, 3)  (4, 4)
 (0, 0)  (5, 1)  (1, 2)   (5, 3)  (5, 4)
 (0, 0)  (6, 1)  (2, 2)   (6, 3)  (6, 4)
 (0, 0)  (7, 1)  (3, 2)   (7, 3)  (7, 4)
 (0, 0)  (1, 1)  (8, 2)   (5, 3)  (8, 4)
 (0, 0)  (2, 1)  (9, 2)   (6, 3)  (9, 4)
 (0, 0)  (3, 1)  (10, 2)  (7, 3)  (5, 4)
 (0, 0)  (4, 1)  (11, 2)  (8, 3)  (6, 4)

In [146]:
J

11×5 Matrix{Vector{Int64}}:
 [1, 1, 1, 1]  [1, 1, 1, 1]  [1, 1, 1, 1]  [1, 1, 1, 1]  [1, 1, 1, 1]
 [1, 1, 1, 1]  [1, 1, 1, 1]  [1, 1, 1, 1]  [1, 1, 1, 1]  [1, 1, 1, 1]
 [1, 1, 1, 1]  [1, 1, 1, 1]  [1, 1, 1, 1]  [1, 1, 1, 1]  [1, 1, 1, 1]
 [1, 1, 1, 1]  [1, 1, 1, 1]  [1, 1, 1, 1]  [2, 2, 2, 0]  [1, 1, 1, 1]
 [1, 1, 1, 1]  [1, 1, 1, 1]  [2, 2, 0, 0]  [1, 1, 1, 1]  [1, 1, 1, 1]
 [1, 1, 1, 1]  [1, 1, 1, 1]  [2, 2, 0, 0]  [1, 1, 1, 1]  [1, 1, 1, 1]
 [1, 1, 1, 1]  [1, 1, 1, 1]  [2, 2, 0, 0]  [1, 1, 1, 1]  [1, 1, 1, 1]
 [1, 1, 1, 1]  [2, 0, 0, 0]  [1, 1, 1, 1]  [2, 2, 2, 0]  [1, 1, 1, 1]
 [1, 1, 1, 1]  [2, 0, 0, 0]  [1, 1, 1, 1]  [2, 2, 2, 0]  [1, 1, 1, 1]
 [1, 1, 1, 1]  [2, 0, 0, 0]  [1, 1, 1, 1]  [2, 2, 2, 0]  [3, 3, 3, 1]
 [1, 1, 1, 1]  [2, 0, 0, 0]  [1, 1, 1, 1]  [2, 2, 2, 0]  [3, 3, 3, 1]